LibraryLab/Controllers/AutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryLab.Data;
using LibraryLab.Models;
using Microsoft.AspNetCore.Authorization;

namespace LibraryLab.Controllers
{
    [Authorize(Roles = "Bibliotecario")]
    public class AutorController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public AutorController(ApplicationDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _webHostEnvironment = environment;
        }

        // GET: Autor
        public async Task<IActionResult> Index()
        {
            return View(await _context.Autor.ToListAsync());
        }

        // GET: Autor/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autor = await _context.Autor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (autor == null)
            {
                return NotFound();
            }

            return View(autor);
        }

        // GET: Autor/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Autor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Biography,Image")] AutorViewModel autor)
        {
            var PhotoExtensions = new string[] { ".jpg", ".jpeg", ".png", ".gif", ".bmp" };

            var extension = Path.GetExtension(autor.Image.FileName).ToLower();

            if (!PhotoExtensions.Contains(extension))
            {
                ModelState.AddModelError("CoverPhoto", "Please, submit a valid image (jpg, jpeg, png, gif, bmp).");
            }
         
            if (ModelState.IsValid)
            {
                var newAutor = new Autor(); //create a new Autor and populate whit fields of the autor parameter
                newAutor.Name = autor.Name;
                newAutor.Biography = autor.Biography;
                newAutor.Image = autor.Image.FileName;

                //save the files in the corresponding folder
                // Save the Image file in the Cover folder
                string coverFileName = Path.GetFileName(autor.Image.FileName);
                string coverFullPath = Path.Combine(_webHostEnvironment.WebRootPath, "ImagemAutor", coverFileName);

                using (var stream = new FileStream(coverFullPath, FileMode.Create))
                {
                    await autor.Image.CopyToAsync(stream);
                }


                // Add the Autor in the database
                _context.Add(newAutor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));




            }
            return View(autor);
        }

        // GET: Autor/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autor = await _context.Autor.FindAsync(id);
            if (autor == null)
            {
                return NotFound();
            }
            return View(autor);
        }

        // POST: Autor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Biography,Image")] Autor autor)
        {
            if (id != autor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(autor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutorExists(autor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(autor);
        }

        // GET: Autor/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autor = await _context.Autor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (autor == null)
            {
                return NotFound();
            }

            return View(autor);
        }

        // POST: Autor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var autor = await _context.Autor.FindAsync(id);
            if (autor != null)
            {
                _context.Autor.Remove(autor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AutorExists(int id)
        {
            return _context.Autor.Any(e => e.Id == id);
        }
    }
}

LibraryLab/Controllers/LivroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryLab.Data;
using LibraryLab.Models;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Authorization;

namespace LibraryLab.Controllers
{
    [Authorize(Roles = "Bibliotecario")]
    public class LivroController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public LivroController(ApplicationDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _webHostEnvironment = environment;
        }

        // GET: Livro
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Livro.Include(l => l.Autor).Include(l => l.Genero);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Livro/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livro
                .Include(l => l.Autor)
                .Include(l => l.Genero)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // GET: Livro/Create
        public IActionResult Create()
        {
            ViewData["AutorId"] = new SelectList(_context.Autor, "Id", "Name");
            ViewData["GeneroId"] = new SelectList(_context.Genero, "Id", "Name");
            ViewData["Estado"] = new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text = "Disponivel", Value = "True"},
                new SelectListItem { Text = "Indisponivel", Value = "False"}
            }, "Value", "Text");
            return View();
        }

        // POST: Livro/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ISBN,Titulo,AutorId,GeneroId,Num_exemplares,Image,Sinopse,Estado")] LivroViewModel livro)
        {
            var PhotoExtensions = new string[] { ".jpg", ".jpeg", ".png", ".gif", ".bmp" };

            var extension = Path.GetExtension(livro.Image.FileName).ToLower();

            if (!PhotoExtensions.Contains(extension))
            {
                ModelState.AddModelError("CoverPhoto", "Please, submit a valid image (jpg, jpeg, png, gif, bmp).");
            }

            if (ModelState.IsValid)
            {
                var newLivro = new Livro(); //create a new Livro and populate whit fields of the livro parameter
                newLivro.ISBN = livro.ISBN;
                newLivro.Titulo = livro.Titulo;
                newLivro.AutorId = livro.AutorId;
                newLivro.GeneroId = livro.GeneroId;
                newLivro.Num_exemplares = livro.Num_exemplares;
                newLivro.Image = livro.Image.FileName;
                newLivro.Sinopse = livro.Sinopse;
                newLivro.Estado = livro.Estado;



                //save the files in the corresponding folder
                // Save the Image file in the Cover folder
                string coverFileName = Path.GetFileName(livro.Image.FileName);
                string coverFullPath = Path.Combine(_webHostEnvironment.WebRootPath, "ImagemLivro", coverFileName);

                using (var stream = new FileStream(coverFullPath, FileMode.Create))
                {
                    await livro.Image.CopyToAsync(stream);
                }


                // Add the Livro in the database
                _context.Add(newLivro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));




            }
            return View(livro);
        }

        // GET: Livro/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livro.FindAsync(id);
            if (livro == null)
            {
                return NotFound();
            }
            ViewData["AutorId"] = new SelectList(_context.Autor, "Id", "Name", livro.AutorId);
            ViewData["GeneroId"] = new SelectList(_context.Genero, "Id", "Name", livro.GeneroId);
            ViewData["Estado"] = new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text = "Disponivel", Value = "True"},
                new SelectListItem { Text = "Indisponivel", Value = "False"}
            }, "Value", "Text");
            
            return View(livro);
        }

        // POST: Livro/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ISBN,Titulo,AutorId,GeneroId,Num_exemplares,Image,Sinopse,Estado")] Livro livro)
        {
            if (id != livro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(livro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LivroExists(livro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AutorId"] = new SelectList(_context.Autor, "Id", "Name", livro.AutorId);
            ViewData["GeneroId"] = new SelectList(_context.Genero, "Id", "Name", livro.GeneroId);
            ViewData["Estado"] = new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text = "Disponivel", Value = "True"},
                new SelectListItem { Text = "Indisponivel", Value = "False"}
            }, "Value", "Text");
            return View(livro);
        }

        // GET: Livro/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livro
                .Include(l => l.Autor)
                .Include(l => l.Genero)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // POST: Livro/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var livro = await _context.Livro.FindAsync(id);
            if (livro != null)
            {
                _context.Livro.Remove(livro);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LivroExists(int id)
        {
            return _context.Livro.Any(e => e.Id == id);
        }
    }
}

LibraryLab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryLab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryLab.styles.css" asp-append-version="true" />
    <style>
        .footer-text {
            font-size: 0.875rem; /* Smaller font size */
            line-height: 1.2; /* Reduced line height */
        }

        .footer {
            background-color: #f8f9fa;
            padding: 20px 0;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/ImagemBiblio/biblioLei.png" alt="Biblioteca LEI" style="width: 100px; height: auto; margin-right: 10px;">
                    Biblioteca LEI
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                        @if (User.IsInRole("Leitor"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Historico">Histórico</a>

                            </li>
                        }
                        @if (User.IsInRole("Bibliotecario"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Livro">Livros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Generoes">Géneros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Autor">Autores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Requisitar">Requisições</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Utilizadores">Utilizadores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TabelaBiblios">Biblioteca</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <br />
    <br />
    <br />
    @{
        var currentUrl = Context.Request.Path.Value.ToLower();
        var isHomePage = string.IsNullOrWhiteSpace(currentUrl) || currentUrl == "/";
    }

    @if (isHomePage)
    {
        <footer class="footer text-muted">
            <div class="container">
                <div class="row footer-text">
                    @if (Model != null && Model.TabelaBiblio != null)
                    {
                        @foreach (var biblio in Model.TabelaBiblio)
                        {
                            <div class="col-md-3">
                                <h6>Localização:</h6>
                                <p>@biblio.Localizacao</p>
                            </div>
                            <div class="col-md-3">
                                <h6>Email:</h6>
                                <p>@biblio.Email</p>
                            </div>
                            <div class="col-md-3">
                                <h6>Tel.:</h6>
                                <p>@biblio.Telefone</p>
                            </div>
                            <div class="col-md-3">
                                <h6>Horário:</h6>
                                <p>@biblio.Horario_abertura h - @biblio.Horario_fecho h</p>
                            </div>
                        }
                    }
                    else
                    {
                        <p class="text-center">Nenhuma informação de biblioteca disponível.</p>
                    }
                </div>
            </div>
        </footer>
    }



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
	<script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>